POST http://localhost:3000/api/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "1234"
}

###

GET http://localhost:3000/api/get_appointment_list/24 HTTP/1.1

###

GET http://localhost:3000/api/get_barber_appointment_by_id/14 HTTP/1.1

